var walletLanguages = {
	'en': {
		'lang-alias': 'English',
		'wallet-title': 'Wallet',
		'open-regular': 'Regular wallet',
		'open-key': 'Open by key',
		'disclaimer': 'This page uses javascript to generate your addresses and sign your transactions within your browser, this means we never receive your private keys, this can be independently verified by reviewing the source code on Github.',
		'open-reminder': '<b>Notice:</b> Please make sure that you remember your account details, otherwise you may lose access to your funds.',
		'open': 'Open',
		'home': 'Home',
		'create': 'Create',
		'broadcast': 'Broadcast',
		'settings': 'Settings',
		'email-address': 'Email address',
		'password': 'Password',
		'password-confirm': 'Confirm password',
		'generate-question': 'Still don\'t have wallet?',
		'generate-it': '<a href="#/create">Generate</a> it!',
		'wif-key': 'WIF Private key',
		'create-wallet': 'Create wallet',
		'show': 'Show',
		'hide': 'Hide',
		'address': 'Address',
		'public-key': 'Public Key',
		'private-key': 'Private Key',
		'broadcast-transaction': 'Broadcast transaction',
		'enter-transaction': 'Enter your signed transaction',
		'wallet-settings': 'Wallet settings',
		'address-type': 'Address Type',
		'wallet-backend': 'Wallet Backend',
		'update': 'Update',
		'wallet-language': 'Wallet Language',
		'version': 'Version:',
		'wallet': 'Wallet',
		'close': 'Close',
		'send': 'Send',
		'history': 'History',
		'keys': 'Keys',
		'reset': 'Reset',
		'available-balance': 'Available balance:',
		'enter-address': 'Enter address',
		'amount': 'Amount',
		'fee': 'Fee',
		'recommended': 'recommended',
		'loading': 'Loading...',
		'send-sure': 'Are you sure?',
		'send-processing': 'Processing...',
		'success': 'Success',
		'failed': 'Failed',
		'send-it': 'Yes, send it!',
		'cancel': 'Cancel',
		'send-warning': 'You are one step away from sending',
		'send-warning-reverse': 'This action <strong>cannot</strong> be reversed. Are you sure about this?',
		'loading-utxo': 'Loading UTXOs...',
		'transaction-creation': 'Creating transaction...',
		'transaction-broadcasted': 'Transaction successfully broadcasted: ',
		'close': 'Close',
		'address-type-changed': 'Address type changed to',
		'backend-switched': 'Backend is switched to',
		'backend-down': 'don\'t seems to be available',
		'wallet-api': 'Wallet API backend',
		'open-wallet': 'Open Wallet',
		'bad-utxo': 'Unsupported UTXO type!',
		'balance-load-failed': 'We couldn\'t load wallet balance!',
		'not-enough-funds': 'You don\'t have enough funds for this transaction!',
		'not-valid-address': 'You must specify valid address!',
		'not-valid-amount': 'You must specify valid amount!',
		'not-valid-fee': 'You must specify valid fee!',
		'bad-priv-key': 'Bad WIF private key!',
		'not-enough-utxo': 'Not enough UTXO :(',
		'broadcast-failed': 'Transaction broadcast failed :(',
		'pass-not-match': 'Your passwords do not match!',
		'pass-too-short': 'Your password must be at least 10 chars long!',
		'bad-email': 'Your email address doesn\'t appear to be valid!',
		'small-fee': 'You should specify fee not less than',
		'scan-qr': 'Scan',
		'scan-modal-title': 'QR Code scanner',
		'webcam-message': 'Please make sure you have a webcam enabled',
		'webcam-loading': 'Loading camera...',
		'outputs-added': 'added to outputs'
	},
	'uk': {
		'lang-alias': 'Ð£ÐºÑ€Ð°Ñ—Ð½ÑÑŒÐºÐ°',
		'wallet-title': 'Ð“Ð°Ð¼Ð°Ð½ÐµÑ†ÑŒ',
		'open-regular': 'Ð—Ð²Ð¸Ñ‡Ð°Ð¹Ð½Ð¸Ð¹ Ð³Ð°Ð¼Ð°Ð½ÐµÑ†ÑŒ',
		'open-key': 'Ð’Ñ–Ð´ÐºÑ€Ð¸Ñ‚Ð¸ ÐºÐ»ÑŽÑ‡ÐµÐ¼',
		'disclaimer': 'Ð¦Ñ ÑÑ‚Ð¾Ñ€Ñ–Ð½ÐºÐ° Ð²Ð¸ÐºÐ¾Ñ€Ð¸ÑÑ‚Ð¾Ð²ÑƒÑ” javascript Ð´Ð»Ñ Ð³ÐµÐ½ÐµÑ€Ð°Ñ†Ñ–Ñ— Ð²Ð°ÑˆÐ¸Ñ… Ð°Ð´Ñ€ÐµÑ Ñ‚Ð° Ð¿Ñ–Ð´Ð¿Ð¸ÑÑƒ Ñ‚Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ñ–Ð¹ Ð²ÑÐµÑ€ÐµÐ´Ð¸Ð½Ñ– Ð±Ñ€Ð°ÑƒÐ·ÐµÑ€Ð°, Ñ†Ðµ Ð¾Ð·Ð½Ð°Ñ‡Ð°Ñ”, Ñ‰Ð¾ Ð¼Ð¸ Ð½Ñ–ÐºÐ¾Ð»Ð¸ Ð½Ðµ Ð¾Ñ‚Ñ€Ð¸Ð¼ÑƒÑ”Ð¼Ð¾ Ð²Ð°ÑˆÑ– Ð¿Ñ€Ð¸Ð²Ð°Ñ‚Ð½Ñ– ÐºÐ»ÑŽÑ‡Ñ–, Ñ†Ðµ Ð¼Ð¾Ð¶Ð½Ð° Ð¿ÐµÑ€ÐµÐ²Ñ–Ñ€Ð¸Ñ‚Ð¸ Ð½ÐµÐ·Ð°Ð»ÐµÐ¶Ð½Ð¾, Ð¿ÐµÑ€ÐµÐ³Ð»ÑÐ½ÑƒÐ²ÑˆÐ¸ Ð²Ð¸Ñ…Ñ–Ð´Ð½Ð¸Ð¹ ÐºÐ¾Ð´ Ð½Ð° Github.',
		'open-reminder': '<b>Ð£Ð²Ð°Ð³Ð°:</b> Ð‘ÑƒÐ´ÑŒ Ð»Ð°ÑÐºÐ° Ð¿ÐµÑ€ÐµÐºÐ¾Ð½Ð°Ð¹Ñ‚ÐµÑÑŒ, Ñ‰Ð¾ Ð²Ð¸ Ð·Ð°Ð¿Ð°Ð¼\'ÑÑ‚Ð°Ð»Ð¸ Ð´Ð°Ð½Ñ– Ð²Ð°ÑˆÐ¾Ð³Ð¾ Ð°ÐºÐ°ÑƒÐ½Ñ‚Ñƒ, Ñ–Ð½Ð°ÐºÑˆÐµ Ð²Ð¸ Ð¼Ð¾Ð¶ÐµÑ‚Ðµ Ð²Ñ‚Ñ€Ð°Ñ‚Ð¸Ñ‚Ð¸ Ð´Ð¾ÑÑ‚ÑƒÐ¿ Ð´Ð¾ Ð²Ð°ÑˆÐ¸Ñ… ÐºÐ¾ÑˆÑ‚Ñ–Ð².',
		'open': 'Ð’Ñ–Ð´ÐºÑ€Ð¸Ñ‚Ð¸',
		'home': 'Ð”Ð¾Ð¼Ñ–Ð²ÐºÐ°',
		'create': 'Ð¡Ñ‚Ð²Ð¾Ñ€Ð¸Ñ‚Ð¸',
		'broadcast': 'Ð¢Ñ€Ð°Ð½ÑÐ»ÑŽÐ²Ð°Ñ‚Ð¸',
		'settings': 'ÐÐ°Ð»Ð°ÑˆÑ‚ÑƒÐ²Ð°Ð½Ð½Ñ',
		'email-address': 'Ð•Ð»ÐµÐºÑ‚Ñ€Ð¾Ð½Ð½Ð° Ð¿Ð¾ÑˆÑ‚Ð°',
		'password': 'ÐŸÐ°Ñ€Ð¾Ð»ÑŒ',
		'password-confirm': 'ÐŸÑ–Ð´Ñ‚Ð²ÐµÑ€Ð´Ñ–Ñ‚ÑŒ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ',
		'generate-question': 'Ð’ÑÐµ Ñ‰Ðµ Ð½Ðµ Ð¼Ð°Ñ”Ñ‚Ðµ Ð³Ð°Ð¼Ð°Ð½Ñ†Ñ?',
		'generate-it': '<a href="#/create">Ð—Ð³ÐµÐ½ÐµÑ€ÑƒÐ¹Ñ‚Ðµ</a> Ð¹Ð¾Ð³Ð¾!',
		'wif-key': 'ÐŸÑ€Ð¸Ð²Ð°Ñ‚Ð½Ð¸Ð¹ ÐºÐ»ÑŽÑ‡ WIF',
		'create-wallet': 'Ð¡Ñ‚Ð²Ð¾Ñ€Ð¸Ñ‚Ð¸ Ð³Ð°Ð¼Ð°Ð½ÐµÑ†ÑŒ',
		'show': 'ÐŸÐ¾ÐºÐ°Ð·Ð°Ñ‚Ð¸',
		'hide': 'Ð¡Ñ…Ð¾Ð²Ð°Ñ‚Ð¸',
		'address': 'ÐÐ´Ñ€ÐµÑÐ°',
		'public-key': 'ÐŸÑƒÐ±Ð»Ñ–Ñ‡Ð½Ð¸Ð¹ ÐšÐ»ÑŽÑ‡',
		'private-key': 'ÐŸÑ€Ð¸Ð²Ð°Ñ‚Ð½Ð¸Ð¹ ÐšÐ»ÑŽÑ‡',
		'broadcast-transaction': 'Ð¢Ñ€Ð°Ð½ÑÐ»ÑŽÐ²Ð°Ñ‚Ð¸ Ñ‚Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ñ–ÑŽ',
		'enter-transaction': 'Ð’Ð²ÐµÐ´Ñ–Ñ‚ÑŒ Ð²Ð°ÑˆÑƒ Ð¿Ñ–Ð´Ð¿Ð¸ÑÐ°Ð½Ñƒ Ñ‚Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ñ–ÑŽ',
		'wallet-settings': 'ÐÐ°Ð»Ð°ÑˆÑ‚ÑƒÐ²Ð°Ð½Ð½Ñ Ð³Ð°Ð¼Ð°Ð½Ñ†Ñ',
		'address-type': 'Ð¢Ð¸Ð¿ ÐÐ´Ñ€ÐµÑÐ¸',
		'wallet-backend': 'Ð‘ÐµÐºÐµÐ½Ð´ Ð“Ð°Ð¼Ð°Ð½Ñ†Ñ',
		'update': 'ÐžÐ½Ð¾Ð²Ð¸Ñ‚Ð¸',
		'wallet-language': 'ÐœÐ¾Ð²Ð° Ð“Ð°Ð¼Ð°Ð½Ñ†Ñ',
		'version': 'Ð’ÐµÑ€ÑÑ–Ñ:',
		'wallet': 'Ð“Ð°Ð¼Ð°Ð½ÐµÑ†ÑŒ',
		'close': 'Ð—Ð°ÐºÑ€Ð¸Ñ‚Ð¸',
		'send': 'ÐÐ°Ð´Ñ–ÑÐ»Ð°Ñ‚Ð¸',
		'history': 'Ð†ÑÑ‚Ð¾Ñ€Ñ–Ñ',
		'keys': 'ÐšÐ»ÑŽÑ‡Ñ–',
		'reset': 'Ð¡ÐºÐ¸Ð½ÑƒÑ‚Ð¸',
		'available-balance': 'Ð”Ð¾ÑÑ‚ÑƒÐ¿Ð½Ð¸Ð¹ Ð±Ð°Ð»Ð°Ð½Ñ:',
		'enter-address': 'Ð’Ð²ÐµÐ´Ñ–Ñ‚ÑŒ Ð°Ð´Ñ€ÐµÑÑƒ',
		'amount': 'Ð¡ÑƒÐ¼Ð°',
		'fee': 'ÐšÐ¾Ð¼Ñ–ÑÑ–Ñ',
		'recommended': 'Ñ€ÐµÐºÐ¾Ð¼ÐµÐ½Ð´Ð¾Ð²Ð°Ð½Ð¾',
		'loading': 'Ð—Ð°Ð²Ð°Ð½Ñ‚Ð°Ð¶ÐµÐ½Ð½Ñ...',
		'send-sure': 'Ð’Ð¸ Ð²Ð¿ÐµÐ²ÐµÐ½ÐµÐ½Ñ–?',
		'send-processing': 'ÐžÐ±Ñ€Ð¾Ð±ÐºÐ°...',
		'success': 'Ð£ÑÐ¿Ñ–Ñ…',
		'failed': 'ÐÐµÐ²Ð´Ð°Ñ‡Ð°',
		'send-it': 'Ð¢Ð°Ðº, Ð½Ð°Ð´Ñ–ÑÐ»Ð°Ñ‚Ð¸!',
		'cancel': 'Ð¡ÐºÐ°ÑÑƒÐ²Ð°Ñ‚Ð¸',
		'send-warning': 'Ð’Ð¸ Ð² Ð¾Ð´Ð½Ð¾Ð¼Ñƒ ÐºÑ€Ð¾Ñ†Ñ– Ð²Ñ–Ð´ Ñ‚Ð¾Ð³Ð¾, Ñ‰Ð¾Ð± Ð½Ð°Ð´Ñ–ÑÐ»Ð°Ñ‚Ð¸',
		'send-warning-reverse': 'Ð¦Ñ Ð´Ñ–Ñ <strong>Ð½Ðµ Ð¼Ð¾Ð¶Ðµ</strong> Ð±ÑƒÑ‚Ð¸ ÑÐºÐ°ÑÐ¾Ð²Ð°Ð½Ð¾ÑŽ. Ð’Ð¸ Ð²Ð¿ÐµÐ²Ð½ÐµÐ½Ñ–?',
		'loading-utxo': 'Ð—Ð°Ð²Ð°Ð½Ñ‚Ð°Ð¶ÐµÐ½Ð½Ñ UTXOs...',
		'transaction-creation': 'Ð¡Ñ‚Ð²Ð¾Ñ€ÐµÐ½Ð½Ñ Ñ‚Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ñ–Ñ—...',
		'transaction-broadcasted': 'Ð¢Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ñ–Ñ ÑƒÑÐ¿Ñ–ÑˆÐ½Ð¾ Ð½Ð°Ð´Ñ–ÑÐ»Ð°Ð½Ð°: ',
		'close': 'Ð—Ð°ÐºÑ€Ð¸Ñ‚Ð¸',
		'address-type-changed': 'Ð¢Ð¸Ð¿ Ð°Ð´Ñ€ÐµÑ Ð·Ð¼Ñ–Ð½ÐµÐ½Ð¸Ð¹ Ð½Ð°',
		'backend-switched': 'Ð‘ÐµÐºÐµÐ½Ð´ Ð·Ð¼Ñ–Ð½ÐµÐ½Ð¸Ð¹ Ð½Ð°',
		'backend-down': 'Ð²Ð¸Ð³Ð»ÑÐ´Ð°Ñ” Ð¼ÐµÑ€Ñ‚Ð²Ð¸Ð¼',
		'wallet-api': 'API Ð‘ÐµÐºÐµÐ½Ð´ Ð³Ð°Ð¼Ð°Ð½Ñ†Ñ',
		'open-wallet': 'Ð’Ñ–Ð´ÐºÑ€Ð¸Ñ‚Ð¸ Ð“Ð°Ð¼Ð°Ð½ÐµÑ†ÑŒ',
		'bad-utxo': 'ÐÐµÐ¿Ñ–Ð´Ñ‚Ñ€Ð¸Ð¼ÑƒÐ²Ð°Ð½Ð¸Ð¹ Ñ‚Ð¸Ð¿ UTXO!',
		'balance-load-failed': 'ÐÐ°Ð¼ Ð½Ðµ Ð²Ð´Ð°Ð»Ð¾ÑÑ Ð·Ð°Ð²Ð°Ð½Ñ‚Ð°Ð¶Ð¸Ñ‚Ð¸ Ð±Ð°Ð»Ð°Ð½Ñ Ð²Ð°ÑˆÐ¾Ð³Ð¾ Ð³Ð°Ð¼Ð°Ð½Ñ†Ñ!',
		'not-enough-funds': 'Ð£ Ð²Ð°Ñ Ð½Ðµ Ð´Ð¾ÑÑ‚Ð°Ñ‚Ð½ÑŒÐ¾ ÐºÐ¾ÑˆÑ‚Ñ–Ð² Ð´Ð»Ñ Ñ†Ñ–Ñ”Ñ— Ñ‚Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ñ–Ñ—!',
		'not-valid-address': 'Ð’Ð¸ Ð¼Ð°Ñ”Ñ‚Ðµ Ð²Ð²ÐµÑÑ‚Ð¸ Ð´Ñ–Ð¹ÑÐ½Ñƒ Ð°Ð´Ñ€ÐµÑÑƒ!',
		'not-valid-amount': 'Ð’Ð¸ Ð¼Ð°Ñ”Ñ‚Ðµ Ð²Ð²ÐµÑÑ‚Ð¸ Ð´Ñ–Ð¹ÑÐ½Ñƒ ÑÑƒÐ¼Ñƒ!',
		'not-valid-fee': 'Ð’Ð¸ Ð¼Ð°Ñ”Ñ‚Ðµ Ð²Ð²ÐµÑÑ‚Ð¸ Ð´Ñ–Ð¹ÑÐ½Ñƒ ÐºÐ¾Ð¼Ñ–ÑÑ–ÑŽ!',
		'bad-priv-key': 'ÐÐµÐ´Ñ–Ð¹ÑÐ½Ð¸Ð¹ WIF Ð¿Ñ€Ð¸Ð²Ð°Ñ‚Ð½Ð¸Ð¹ ÐºÐ»ÑŽÑ‡ WIF!',
		'not-enough-utxo': 'ÐÐµ Ð´Ð¾ÑÑ‚Ð°Ñ‚Ð½ÑŒÐ¾ UTXO :(',
		'broadcast-failed': 'ÐÐµ Ð²Ð´Ð°Ð»Ð¾ÑÑ Ñ‚Ñ€Ð°Ð½ÑÐ»ÑŽÐ²Ð°Ñ‚Ð¸ Ñ‚Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ñ–ÑŽ :(',
		'pass-not-match': 'ÐŸÐ°Ñ€Ð¾Ð»Ñ– Ð½Ðµ Ð½Ðµ Ð·Ð±Ñ–Ð³Ð°ÑŽÑ‚ÑŒÑÑ!',
		'pass-too-short': 'Ð’Ð°Ñˆ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ Ð¿Ð¾Ð²Ð¸Ð½ÐµÐ½ Ð±ÑƒÑ‚Ð¸ Ð½Ðµ Ð¼ÐµÐ½ÑˆÐµ 10 ÑÐ¸Ð¼Ð²Ð¾Ð»Ñ–Ð²!',
		'bad-email': 'Ð¡Ñ…Ð¾Ð¶Ðµ, Ñ‰Ð¾ Ð²Ð¸ Ð²Ð²ÐµÐ»Ð¸ Ð½Ðµ Ð´Ñ–Ð¹ÑÐ½Ñƒ Ð¿Ð¾ÑˆÑ‚Ð¾Ð²Ñƒ ÑÐºÑ€Ð¸Ð½ÑŒÐºÑƒ!',
		'small-fee': 'Ð’Ð¸ Ð¼Ð°Ñ”Ñ‚Ðµ Ð·Ð°Ð´Ð°Ñ‚Ð¸ ÐºÐ¾Ð¼Ñ–ÑÑ–ÑŽ Ð½Ðµ Ð¼ÐµÐ½ÑˆÐµ Ð½Ñ–Ð¶',
		'scan-qr': 'Ð¡ÐºÐ°Ð½ÑƒÐ²Ð°Ñ‚Ð¸',
		'scan-modal-title': 'Ð—Ñ‡Ð¸Ñ‚ÑƒÐ²Ð°Ñ‡ QR ÐºÐ¾Ð´Ñƒ',
		'webcam-message': 'Ð‘ÑƒÐ´ÑŒ Ð»Ð°ÑÐºÐ°, Ð¿ÐµÑ€ÐµÐºÐ¾Ð½Ð°Ð¹Ñ‚ÐµÑÑ, Ñ‰Ð¾ Ñƒ Ð²Ð°Ñ ÑƒÐ²Ñ–Ð¼ÐºÐ½ÐµÐ½Ð° Ð²ÐµÐ±-ÐºÐ°Ð¼ÐµÑ€Ð°',
		'webcam-loading': 'Ð—Ð°Ð²Ð°Ð½Ñ‚Ð°Ð¶ÐµÐ½Ð½Ñ ÐºÐ°Ð¼ÐµÑ€Ð¸...',
		'outputs-added': 'Ð´Ð¾Ð´Ð°Ð½Ð¾ Ð´Ð¾ Ð²Ð¸Ñ…Ð¾Ð´Ñ–Ð²'
	},
	'id': {
		'lang-alias': 'Indonesian',
		'wallet-title' : 'Wallet',
		'open-regular': 'Buka dompet',
		'open-key': 'Buka dengan kunci',
		'disclaimer': 'Halaman ini menggunakan javascript untuk menghasilkan alamat dompet dan menandatangani transaksi Anda, ini berarti kami tidak pernah menerima kunci domprt pribadi Anda, ini diverifikasi secara terpisah dengan melihat sumber code di Github.',
		'open-reminder': '<b>Perhatikan:</b> Pastikan Anda mencadangkan detail dompet anda, jika tidak, Anda dapat kehilangan akses ke dana Anda.',
		'open': 'Buka',
		'home': 'Halaman depan',
		'create': 'Membuat',
		'broadcast': 'Siaran',
		'settings': 'Pengaturan',
		'email-address': 'Alamat Email',
		'password': 'Kata Kunci',
		'password-confirm': 'Konfirmasi Kata Kunci',
		'generate-question': 'sudah punya dompet belum punya dompet?',
		'generate-it': '<a href="#/create">Membuat</a> dompet!',
		'wif-key': 'WIF Kunci Pribadi',
		'create-wallet': 'Membuat Dompet',
		'show': 'Tunjukan',
		'hide': 'Sembunyikan',
		'address': 'Alamat',
		'public-key': 'Kunci Publik',
		'private-key': 'Kunci Pribadi',
		'broadcast-transaction': 'Siaran transaksi',
		'enter-transaction': 'masuk transaksi',
		'wallet-settings': 'Pengaturan Dompet',
		'address-type': 'Tipe Alamat',
		'wallet-backend': 'Backend Dompet',
		'update': 'Pembaharuan',
		'wallet-language': 'Bahasa dompet',
		'version': 'Versi:',
		'wallet': 'Dompet',
		'close': 'Tutup',
		'send': 'Kirim',
		'history': 'Riwayat',
		'keys': 'Kunci',
		'reset': 'Mulai ulang',
		'available-balance': 'Saldo tersedia:',
		'enter-address': 'Masukan Alamat',
		'amount': 'Jumlah',
		'fee': 'Biaya',
		'recommended': 'Rekomendasi',
		'loading': 'Memuat...',
		'send-sure': 'Apakah kamu Yakin?',
		'send-processing': 'Memproses...',
		'success': 'Sukses',
		'failed': 'Gagal',
		'send-it': 'Ya, Kirim sekarang!',
		'cancel': 'Batalkan',
		'send-warning': 'Tinggal selangkah lagi',
		'send-warning-reverse': 'Tetap kirim <strong>Batalkan</strong> bisa kembali. Apa kamu sudah yakin?',
		'loading-utxo': 'Memuat UTXOs...',
		'transaction-creation': 'Membuat Transaksi...',
		'transaction-broadcasted': 'Transaksi berhasil dikirim: ',
		'close': 'Tutup',
		'address-type-changed': 'Ganti tipe alamat',
		'backend-switched': 'Backend berpindah ke',
		'backend-down': 'Backend sepertinya tidak ada',
		'wallet-api': 'Dompet API',
		'open-wallet': 'Buka Dompet',
		'bad-utxo': 'Tidak mendukung tipe UTXO!',
		'balance-load-failed': 'Kami tidak bisa menampilkan jumlah saldo!',
		'not-enough-funds': 'Kamu tidak punya cukup saldo untuk transaksi ini!',
		'not-valid-address': 'Kamu harus memasukkan wallet yang benar!',
		'not-valid-amount': 'Kamu harus memasukkan jumlah yang benar!',
		'not-valid-fee': 'Kamu harus memasukkan biaya yang benar!',
		'bad-priv-key': 'Kunci Pribadi Salah!',
		'not-enough-utxo': 'Tidak Cukup UTXO :(',
		'broadcast-failed': 'Siaran transaksi gagal :(',
		'pass-not-match': 'Password anda tidak cocok!',
		'pass-too-short': 'Kata sandi Anda setidaknya harus sepanjang 10 karakter!',
		'bad-email': 'Alamat email Anda tampaknya tidak valid!',
		'small-fee': 'Biaya terlalu kecil'
	},
	'ja': {
		'lang-alias': 'æ—¥æœ¬èªž',
		'open-regular': 'é€šå¸¸ã‚¦ã‚©ãƒ¬ãƒƒãƒˆ',
		'open-key': 'ã‚­ãƒ¼ã§é–‹ã',
		'disclaimer': 'ã“ã®ãƒšãƒ¼ã‚¸ã§ã¯javascriptã‚’ä½¿ç”¨ã—ã¦ã‚¢ãƒ‰ãƒ¬ã‚¹ã‚’ç”Ÿæˆã—ã€ãƒ–ãƒ©ã‚¦ã‚¶å†…ã§å–å¼•ã«ç½²åã—ã¾ã™ã€‚ãã®ãŸã‚ã€ç§˜å¯†éµã‚’é€ä¿¡ã™ã‚‹ã“ã¨ã¯ã‚ã‚Šã¾ã›ã‚“ã€‚ã“ã‚Œã¯Githubã®ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰ã§ç¢ºèªã§ãã¾ã™ã€‚',
		'open-reminder': '<b>ãŠçŸ¥ã‚‰ã›:</b> ã‚¢ã‚«ã‚¦ãƒ³ãƒˆè©³ç´°ã‚’å¿˜ã‚Œãªã„ã‚ˆã†ã«ã—ã¦ãã ã•ã„ã€‚è³‡é‡‘ã«ã‚¢ã‚¯ã‚»ã‚¹ã§ããªããªã‚‹å¯èƒ½æ€§ãŒã‚ã‚Šã¾ã™ã€‚',
		'open': 'é–‹ã',
		'home': 'ãƒ›ãƒ¼ãƒ ',
		'create': 'ä½œæˆ',
		'broadcast': 'ãƒ–ãƒ­ãƒ¼ãƒ‰ã‚­ãƒ£ã‚¹ãƒˆ',
		'settings': 'è¨­å®š',
		'email-address': 'ãƒ¡ãƒ¼ãƒ«ã‚¢ãƒ‰ãƒ¬ã‚¹',
		'password': 'ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰',
		'password-confirm': 'ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰ç¢ºèª',
		'generate-question': 'ã¾ã ã‚¦ã‚©ãƒ¬ãƒƒãƒˆã‚’ãŠæŒã¡ã§ã¯ã‚ã‚Šã¾ã›ã‚“ã‹ï¼Ÿ',
		'generate-it': '<a href="#/create">ä½œã‚Šã¾ã™ï¼</a> ',
		'wif-key': 'WIFå½¢å¼ã®ç§˜å¯†éµ',
		'create-wallet': 'ã‚¦ã‚©ãƒ¬ãƒƒãƒˆä½œæˆ',
		'show': 'è¦‹ã‚‹',
		'hide': 'éš ã™',
		'address': 'ã‚¢ãƒ‰ãƒ¬ã‚¹',
		'public-key': 'å…¬é–‹éµ (ãƒ‘ãƒ–ãƒªãƒƒã‚¯ã‚­ãƒ¼)',
		'private-key': 'ç§˜å¯†éµ (ãƒ—ãƒ©ã‚¤ãƒ™ãƒ¼ãƒˆã‚­ãƒ¼)',
		'broadcast-transaction': 'å–å¼•ã®ãƒ–ãƒ­ãƒ¼ãƒ‰ã‚­ãƒ£ã‚¹ãƒˆ',
		'enter-transaction': 'å–å¼•ã‚’å…¥åŠ›ã—ã¦ãã ã•ã„',
		'wallet-settings': 'ã‚¦ã‚©ãƒ¬ãƒƒãƒˆè¨­å®š',
		'address-type': 'ã‚¢ãƒ‰ãƒ¬ã‚¹å½¢å¼',
		'wallet-backend': 'ã‚¦ã‚©ãƒ¬ãƒƒãƒˆãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰',
		'update': 'æ›´æ–°',
		'wallet-language': 'ã‚¦ã‚©ãƒ¬ãƒƒãƒˆè¨€èªž',
		'version': 'ãƒãƒ¼ã‚¸ãƒ§ãƒ³:',
		'wallet': 'ã‚¦ã‚©ãƒ¬ãƒƒãƒˆ',
		'close': 'é–‰ã˜ã‚‹',
		'send': 'é€ä¿¡',
		'history': 'å±¥æ­´',
		'keys': 'ã‚­ãƒ¼',
		'reset': 'ãƒªã‚»ãƒƒãƒˆ',
		'available-balance': 'åˆ©ç”¨å¯èƒ½:',
		'enter-address': 'ã‚¢ãƒ‰ãƒ¬ã‚¹ã‚’å…¥åŠ›ã—ã¦ãã ã•ã„',
		'amount': 'é‡‘é¡',
		'fee': 'æ‰‹æ•°æ–™',
		'recommended': 'æŽ¨å¥¨',
		'loading': 'èª­ã¿è¾¼ã¿ä¸­...',
		'send-sure': 'é€ä¿¡ã—ã¦ã‚ˆã‚ã—ã„ã§ã™ã‹ï¼Ÿ',
		'send-processing': 'å‡¦ç†ä¸­...',
		'success': 'æˆåŠŸ',
		'failed': 'å¤±æ•—',
		'send-it': 'ã¯ã„ã€é€ä¿¡ã—ã¾ã™ï¼',
		'cancel': 'ã‚­ãƒ£ãƒ³ã‚»ãƒ«',
		'send-warning': 'é€ä¿¡ã¾ã§ã‚ã¨å°‘ã—ã§ã™ã€‚',
		'send-warning-reverse': 'ã“ã®æ“ä½œã¯<strong>å–æ¶ˆã§ãã¾ã›ã‚“ã€‚</strong>æœ¬å½“ã«ã‚ˆã‚ã—ã„ã§ã™ã‹ï¼Ÿ',
		'loading-utxo': 'UTXOsã‚’èª­ã¿è¾¼ã‚“ã§ã„ã¾ã™...',
		'transaction-creation': 'å–å¼•ã‚’ä½œæˆä¸­...',
		'transaction-broadcasted': 'å–å¼•ã®ãƒ–ãƒ­ãƒ¼ãƒ‰ã‚­ãƒ£ã‚¹ãƒˆã«æˆåŠŸã—ã¾ã—ãŸ: ',
		'close': 'é–‰ã˜ã‚‹',
		'address-type-changed': 'ã‚¢ãƒ‰ãƒ¬ã‚¹å½¢å¼ãŒæ¬¡ã«å¤‰æ›´ã•ã‚Œã¾ã—ãŸ',
		'backend-switched': 'ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰ãŒæ¬¡ã«å¤‰æ›´ã•ã‚Œã¾ã—ãŸ',
		'backend-down': 'ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰ä½¿ç”¨ä¸å¯èƒ½',
		'wallet-api': 'ã‚¦ã‚©ãƒ¬ãƒƒãƒˆAPIãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰',
		'open-wallet': 'ã‚¦ã‚©ãƒ¬ãƒƒãƒˆã‚’é–‹ã',
		'bad-utxo': 'ã‚µãƒãƒ¼ãƒˆã•ã‚Œã¦ã„ãªã„UTXOã‚¿ã‚¤ãƒ—ã§ã™ï¼',
		'balance-load-failed': 'ã‚¦ã‚©ãƒ¬ãƒƒãƒˆæ®‹é«˜ãŒèª­ã¿è¾¼ã‚ã¾ã›ã‚“ã§ã—ãŸï¼',
		'not-enough-funds': 'å–å¼•ã«å¯¾ã—ã¦è³‡é‡‘ãŒä¸è¶³ã—ã¦ã„ã¾ã™',
		'not-valid-address': 'æ­£ã—ã„ã‚¢ãƒ‰ãƒ¬ã‚¹ã‚’æŒ‡å®šã—ã¦ãã ã•ã„ï¼',
		'not-valid-amount': 'æ­£ã—ã„é‡‘é¡ã‚’æŒ‡å®šã—ã¦ãã ã•ã„ï¼',
		'not-valid-fee': 'æ­£ã—ã„æ‰‹æ•°æ–™ã‚’æŒ‡å®šã—ã¦ãã ã•ã„ï¼',
		'bad-priv-key': 'ç§˜å¯†éµãŒé–“é•ã£ã¦ã„ã¾ã™',
		'not-enough-utxo': 'UTXOãŒä¸è¶³ã—ã¦ã„ã¾ã™ :(',
		'broadcast-failed': 'å–å¼•ã®ãƒ–ãƒ­ãƒ¼ãƒ‰ã‚­ãƒ£ã‚¹ãƒˆã«å¤±æ•—ã—ã¾ã—ãŸ :(',
		'pass-not-match': 'ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰ãŒé–“é•ã£ã¦ã„ã¾ã™ï¼',
		'pass-too-short': 'ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰ã¯10æ–‡å­—ä»¥ä¸Šå¿…è¦ã§ã™ï¼',
		'bad-email': 'ãƒ¡ãƒ¼ãƒ«ã‚¢ãƒ‰ãƒ¬ã‚¹ãŒç™»éŒ²ã•ã‚Œã¦ã„ã¾ã›ã‚“ï¼',
		'small-fee': 'æœ€ä½Žæ‰‹æ•°æ–™ã¯'
	},
	'zh': {
		'lang-alias': 'ç®€ä½“ä¸­æ–‡',
		'wallet-title': 'ç½‘é¡µé’±åŒ…',
		'open-regular': 'æ™®é€šé’±åŒ…',
		'open-key': 'å¯†é’¥é’±åŒ…',
		'disclaimer': 'æ­¤é¡µé¢é€šè¿‡javascriptè„šæœ¬åœ¨æµè§ˆå™¨ä¸­ç”Ÿæˆåœ°å€å¹¶ä¸ºäº¤æ˜“ç­¾åï¼Œè¿™æ„å‘³ç€æˆ‘ä»¬ä¸ä¼šå¹¶ä¸”æ— æ³•ä¿å­˜æ‚¨çš„ç§é’¥ï¼Œæ‚¨å¯é€šè¿‡æˆ‘ä»¬å…¬å¸ƒåœ¨Githubä¸Šçš„æºç æ¥éªŒè¯ç›¸å…³å†…å®¹çš„æœ‰æ•ˆæ€§.',
		'open-reminder': '<b>æé†’:</b> æ— éœ€æ³¨å†Œï¼Œä½†è¯·ç‰¢è®°æ‚¨çš„é‚®ç®±ä¸Žå¯†ç ï¼Œå®ƒä»¬è¢«ä½œä¸ºå¸æˆ·ç´¢å¼•ï¼Œç³–é“¾å®˜æ–¹ä¸ä¿å­˜ä»»ä½•æ‚¨çš„æ•°æ®ï¼Œæ‰€ä»¥æ— æ³•æä¾›å¸å·æ‰¾å›žåŠŸèƒ½ã€‚',
		'open': 'æ‰“å¼€',
		'home': 'é¦–é¡µ',
		'create': 'åˆ›å»º',
		'broadcast': 'å¹¿æ’­',
		'settings': 'è®¾ç½®',
		'email-address': 'é‚®ç®±åœ°å€',
		'password': 'å¯†ç ',
		'password-confirm': 'ç¡®è®¤å¯†ç ',
		'generate-question': 'è¿˜æœªæ‹¥æœ‰é’±åŒ…å—?',
		'generate-it': '<a href="#/create">åˆ›å»ºä¸€ä¸ª</a>!',
		'wif-key': 'WIFç§é’¥',
		'create-wallet': 'åˆ›å»ºé’±åŒ…',
		'show': 'æ˜¾ç¤º',
		'hide': 'éšè—',
		'address': 'åœ°å€',
		'public-key': 'å…¬é’¥',
		'private-key': 'ç§é’¥',
		'broadcast-transaction': 'å¹¿æ’­äº¤æ˜“',
		'enter-transaction': 'è¾“å…¥äº¤æ˜“ç­¾å',
		'wallet-settings': 'é’±åŒ…è®¾ç½®',
		'address-type': 'åœ°å€ç±»åž‹',
		'wallet-backend': 'é’±åŒ…æŽ¥å£',
		'update': 'æ›´æ–°',
		'wallet-language': 'é’±åŒ…è¯­è¨€',
		'version': 'ç‰ˆæœ¬:',
		'wallet': 'é’±åŒ…',
		'close': 'å…³é—­',
		'send': 'å‘é€',
		'history': 'åŽ†å²',
		'keys': 'å¯†é’¥',
		'reset': 'é‡ç½®',
		'available-balance': 'å¯ç”¨ä½™é¢:',
		'enter-address': 'è¾“å…¥åœ°å€',
		'amount': 'æ•°é‡',
		'fee': 'äº¤æ˜“è´¹ç”¨',
		'recommended': 'æŽ¨è',
		'loading': 'åŠ è½½ä¸­...',
		'send-sure': 'ä½ ç¡®å®šå—?',
		'send-processing': 'å¤„ç†ä¸­...',
		'success': 'æˆåŠŸ',
		'failed': 'å¤±è´¥',
		'send-it': 'ç¡®å®šï¼Œå‘é€!',
		'cancel': 'å–æ¶ˆ',
		'send-warning': 'ç¦»äº¤æ˜“å‘é€ä»…ä¸€æ­¥ä¹‹é¥',
		'send-warning-reverse': 'æ­¤æ“ä½œ<strong>ä¸å¯é€†è½¬</strong>ï¼Œä½ ç¡®å®šå—?',
		'loading-utxo': 'åŠ è½½UTXOä¸­...',
		'transaction-creation': 'åˆ›å»ºäº¤æ˜“ä¸­...',
		'transaction-broadcasted': 'äº¤æ˜“å·²æˆåŠŸå¹¿æ’­: ',
		'close': 'å…³é—­',
		'address-type-changed': 'åœ°å€ç±»åž‹åˆ‡æ¢è‡³',
		'backend-switched': 'åŽç«¯æŽ¥å£å·²åˆ‡æ¢è‡³',
		'backend-down': 'ä¼¼ä¹Žä¸å¯ç”¨',
		'wallet-api': 'é’±åŒ…APIæŽ¥å£',
		'open-wallet': 'æ‰“å¼€é’±åŒ…',
		'bad-utxo': 'ä¸æ”¯æŒçš„UTXOç±»åž‹!',
		'balance-load-failed': 'é’±åŒ…å¯ç”¨ä½™é¢åŠ è½½å¤±è´¥!',
		'not-enough-funds': 'å¯ç”¨ä½™é¢ä¸è¶³ä»¥æ”¯æŒæœ¬æ¬¡äº¤æ˜“!',
		'not-valid-address': 'è¯·ä½¿ç”¨æœ‰æ•ˆçš„é’±åŒ…åœ°å€!',
		'not-valid-amount': 'è¯·ä½¿ç”¨æœ‰æ•ˆçš„æ•°é‡!',
		'not-valid-fee': 'è¯·æŒ‡å®šæœ‰æ•ˆçš„æ‰‹ç»­è´¹ç”¨é‡‘é¢!',
		'bad-priv-key': 'é”™è¯¯çš„WIFç§é’¥!',
		'not-enough-utxo': 'æ²¡æœ‰è¶³å¤Ÿçš„UTXO :(',
		'broadcast-failed': 'äº¤æ˜“å¹¿æ’­å¤±è´¥ :(',
		'pass-not-match': 'ä¸¤æ¬¡è¾“å…¥çš„å¯†ç ä¸åŒ¹é…!',
		'pass-too-short': 'å¯†ç ä¸èƒ½å°‘äºŽ10ä¸ªå­—ç¬¦!',
		'bad-email': 'è¯·ä½¿ç”¨æœ‰æ•ˆçš„ç”µå­é‚®ä»¶æ ¼å¼!',
		'small-fee': 'æ‰‹ç»­è´¹é‡‘é¢ä¸èƒ½ä½ŽäºŽ'
	},
	'es': {
		'lang-alias': 'EspaÃ±ol',
		'wallet-title': 'Cartera',
		'open-regular': 'Cartera regular',
		'open-key': 'Abrir con llave',
		'disclaimer': 'Esta pÃ¡gina utiliza Javascript para generar sus direcciones y firmar sus transacciones en su navegador, Esto implica que nunca recibimos sus claves privada, Esto puede ser verificado independientemente por medio de la revisiÃ³n el cÃ³digo de fuente en Github.',
		'open-reminder': '<b>Aviso:</b> Por favor asegÃºrese que se acuerda sus detalles de cuenta, podrÃ­a perder el acceso de los fondos',
		'open': 'Abrir',
		'home': 'PÃ¡gina Inicial',
		'create': 'Crear',
		'broadcast': 'Transmitir',
		'settings': 'Configuraciones',
		'email-address': 'Correo electrÃ³nico',
		'password': 'ContraseÃ±a',
		'password-confirm': 'Confirma la contraseÃ±a',
		'generate-question': 'todavia no tienes cartera?',
		'generate-it': '<a href="#/crear">Generate</a> lo!',
		'wif-key': 'WIF Clave privada',
		'create-wallet': 'Crear cartera',
		'show': 'Mostrar',
		'hide': 'Esconder',
		'address': 'DirecciÃ³n',
		'public-key': 'Clave pÃºblica',
		'private-key': 'Clave privada',
		'broadcast-transaction': 'Transmitir transacciÃ³n',
		'enter-transaction': 'Introduzca sus transaccion firmado',
		'wallet-settings': 'ConfiguraciÃ³n de la cartera',
		'address-type': 'Tipo de direcciÃ³n',
		'wallet-backend': 'Cartera Backend',
		'update': 'ActualizaciÃ³n',
		'wallet-language': 'Language de la cartera',
		'version': 'VersiÃ³n:',
		'wallet': 'Cartera',
		'close': 'Cerrar',
		'send': 'Enviar',
		'history': 'historia',
		'keys': 'Llaves',
		'reset': 'Reiniciar',
		'available-balance': 'Saldo disponible:',
		'enter-address': 'Introduce direcciÃ³n',
		'amount': 'Cantidad',
		'fee': 'Cuota',
		'recommended': 'recomendado',
		'loading': 'Cargando...',
		'send-sure': 'Â¿EstÃ¡s seguro?',
		'send-processing': 'Procesamiento...',
		'success': 'Ã©xito',
		'failed': 'fallÃ³',
		'send-it': 'sÃ­, envÃ­alo!',
		'cancel': 'Cancelo',
		'send-warning': 'EstÃ¡s a un paso de envÃ­o',
		'send-warning-reverse': 'esta acciÃ³n <strong>no puede</strong> ser revertida. Â¿EstÃ¡s seguro de esto?',
		'loading-utxo': 'Cargando UTXOs...',
		'transaction-creation': 'CreaciÃ³n de transacciÃ³n...',
		'transaction-broadcasted': 'TransacciÃ³n transmitida con Ã©xito: ',
		'close': 'Cerrar',
		'address-type-changed': 'Tipo de direcciÃ³n cambiado a',
		'backend-switched': 'Backend se cambia a',
		'backend-down': 'no parece estar disponible',
		'wallet-api': 'Backend de cartera API',
		'open-wallet': 'Abra la cartera',
		'bad-utxo': 'Tipo UTXO no compatible',
		'balance-load-failed': 'Â¡No pudimos cargar el saldo de la cartera!',
		'not-enough-funds': 'Â¡No tienes suficientes fondos para esta transacciÃ³n!',
		'not-valid-address': 'Â¡Debe especificar una direcciÃ³n vÃ¡lida!',
		'not-valid-amount': 'Â¡Debe especificar la cantidad vÃ¡lida!',
		'not-valid-fee': 'Debe especificar vÃ¡lida cuota!',
		'bad-priv-key': 'Mala WIF clave privada!',
		'not-enough-utxo': 'No hay suficiente UTXO :(',
		'broadcast-failed': 'La transacciÃ³n transmitiÃ³ fallado :(',
		'pass-not-match': 'Â¡Tus contraseÃ±as no coinciden!',
		'pass-too-short': 'Su contraseÃ±a debe tener al menos 10 caracteres!',
		'bad-email': 'Â¡Tu direcciÃ³n de correo electrÃ³nico no parece ser vÃ¡lida!',
		'small-fee': 'Debe especificar fee no menos de'
	},
	'ru': {
		'lang-alias': 'Ð ÑƒÑÑÐºÐ¸Ð¹',
		'wallet-title': 'ÐšÐ¾ÑˆÐµÐ»ÐµÐº',
		'open-regular': 'ÐžÐ±Ñ‹Ñ‡Ð½Ñ‹Ð¹ ÐºÐ¾ÑˆÐµÐ»ÐµÐº',
		'open-key': 'ÐžÑ‚ÐºÑ€Ñ‹Ñ‚ÑŒ ÐºÐ»ÑŽÑ‡Ð¾Ð¼',
		'disclaimer': 'Ð­Ñ‚Ð° ÑÑ‚Ñ€Ð°Ð½Ð¸Ñ†Ð° Ð¸ÑÐ¿Ð¾Ð»ÑŒÐ·ÑƒÐµÑ‚ javascript Ð´Ð»Ñ Ð³ÐµÐ½ÐµÑ€Ð°Ñ†Ð¸Ð¸ Ð’Ð°ÑˆÐµÐ³Ð¾ Ð°Ð´Ñ€ÐµÑÐ° Ð¸ Ð¿Ð¾Ð´Ð¿Ð¸ÑÐ¸ Ð’Ð°ÑˆÐ¸Ñ… Ñ‚Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ð¸Ð¸Ð¹ Ð²Ð½ÑƒÑ‚Ñ€Ð¸ Ð±Ñ€Ð°ÑƒÐ·ÐµÑ€Ð°, ÑÑ‚Ð¾ Ð·Ð½Ð°Ñ‡Ð¸Ñ‚, Ñ‡Ñ‚Ð¾ Ð¼Ñ‹ Ð½Ð¸ÐºÐ¾Ð³Ð´Ð° Ð½Ðµ Ð¿Ð¾Ð»ÑƒÑ‡Ð°ÐµÐ¼ Ð’Ð°ÑˆÐ¸ Ð¿Ñ€Ð¸Ð²Ð°Ñ‚Ð½Ñ‹Ðµ ÐºÐ»ÑŽÑ‡Ð¸, Ð¸ ÑÑ‚Ð¾ Ð¼Ð¾Ð¶Ð½Ð¾ Ð½ÐµÐ·Ð°Ð²Ð¸ÑÐ¸Ð¼Ð¾ Ð¿Ñ€Ð¾Ð²ÐµÑ€Ð¸Ñ‚ÑŒ, Ð¿Ñ€Ð¾Ñ‡Ð¸Ñ‚Ð°Ð² Ð¸ÑÑ…Ð¾Ð´Ð½Ñ‹Ð¹ ÐºÐ¾Ð´ Ð½Ð° GitHub.',
		'open-reminder': '<b>Ð’Ð½Ð¸Ð¼Ð°Ð½Ð¸Ðµ:</b> ÐŸÐ¾Ð¶Ð°Ð»ÑƒÐ¹ÑÑ‚Ð° ÑƒÐ±ÐµÐ´Ð¸Ñ‚ÐµÑÑŒ, Ñ‡Ñ‚Ð¾ Ð’Ñ‹ Ð·Ð°Ð¿Ð¾Ð¼Ð½Ð¸Ð»Ð¸ Ð´ÐµÑ‚Ð°Ð»Ð¸ Ð²Ð°ÑˆÐµÐ³Ð¾ Ð°ÐºÐºÐ°ÑƒÐ½Ñ‚Ð°, Ð¸Ð½Ð°Ñ‡Ðµ Ð’Ñ‹ Ð¼Ð¾Ð¶ÐµÑ‚Ðµ Ð¿Ð¾Ñ‚ÐµÑ€ÑÑ‚ÑŒ Ð´Ð¾ÑÑ‚ÑƒÐ¿ Ðº ÑÐ²Ð¾Ð¸Ð¼ Ð´ÐµÐ½ÐµÐ¶Ð½Ñ‹Ð¼ ÑÑ€ÐµÐ´ÑÑ‚Ð²Ð°Ð¼.',
		'open': 'ÐžÑ‚ÐºÑ€Ñ‹Ñ‚ÑŒ',
		'home': 'Ð”Ð¾Ð¼Ð¾Ð¹',
		'create': 'Ð¡Ð¾Ð·Ð´Ð°Ñ‚ÑŒ',
		'broadcast': 'Ð¢Ñ€Ð°Ð½ÑÐ»Ð¸Ñ€Ð¾Ð²Ð°Ñ‚ÑŒ',
		'settings': 'ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸',
		'email-address': 'Ð­Ð»ÐµÐºÑ‚Ñ€Ð¾Ð½Ð½Ð°Ñ Ð¿Ð¾Ñ‡Ñ‚Ð°',
		'password': 'ÐŸÐ°Ñ€Ð¾Ð»ÑŒ',
		'password-confirm': 'ÐŸÐ¾Ð´Ñ‚Ð²ÐµÑ€Ð´Ð¸Ñ‚ÑŒ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ',
		'generate-question': 'Ð’ÑÑ‘ ÐµÑ‰Ðµ Ð½ÐµÑ‚Ñƒ ÐºÐ¾ÑˆÐµÐ»ÑŒÐºÐ°?',
		'generate-it': '<a href="#/create">Ð¡Ð³ÐµÐ½ÐµÑ€Ð¸Ñ€Ð¾Ð²Ð°Ñ‚ÑŒ</a> ÐµÐ³Ð¾!',
		'wif-key': 'ÐŸÑ€Ð¸Ð²Ð°Ñ‚Ð½Ñ‹Ð¹ ÐºÐ»ÑŽÑ‡ WIF',
		'create-wallet': 'Ð¡Ð¾Ð·Ð´Ð°Ñ‚ÑŒ ÐºÐ¾ÑˆÐµÐ»ÐµÐº',
		'show': 'ÐŸÐ¾ÐºÐ°Ð·Ð°Ñ‚ÑŒ',
		'hide': 'Ð¡Ð¿Ñ€ÑÑ‚Ð°Ñ‚ÑŒ',
		'address': 'ÐÐ´Ñ€ÐµÑ',
		'public-key': 'ÐŸÑƒÐ±Ð»Ð¸Ñ‡Ð½Ñ‹Ð¹ ÐšÐ»ÑŽÑ‡',
		'private-key': 'ÐŸÑ€Ð¸Ð²Ð°Ñ‚Ð½Ñ‹Ð¹ ÐšÐ»ÑŽÑ‡',
		'broadcast-transaction': 'Ð¢Ñ€Ð°Ð½ÑÐ»Ð¸Ñ€Ð¾Ð²Ð°Ñ‚ÑŒ Ñ‚Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ð¸ÑŽ',
		'enter-transaction': 'Ð’Ð²ÐµÐ´Ð¸Ñ‚Ðµ Ð’Ð°ÑˆÑƒ Ð¿Ð¾Ð´Ð¿Ð¸ÑÐ°Ð½Ð½ÑƒÑŽ Ñ‚Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ð¸ÑŽ',
		'wallet-settings': 'ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸ ÐºÐ¾ÑˆÐµÐ»ÑŒÐºÐ°',
		'address-type': 'Ð¢Ð¸Ð¿ ÐÐ´Ñ€ÐµÑÐ°',
		'wallet-backend': 'Ð‘ÑÐºÑÐ½Ð´ ÐšÐ¾ÑˆÐµÐ»ÑŒÐºÐ°',
		'update': 'ÐžÐ±Ð½Ð¾Ð²Ð¸Ñ‚ÑŒ',
		'wallet-language': 'Ð¯Ð·Ñ‹Ðº ÐšÐ¾ÑˆÐµÐ»ÑŒÐºÐ°',
		'version': 'Ð’ÐµÑ€ÑÐ¸Ñ:',
		'wallet': 'ÐšÐ¾ÑˆÐµÐ»ÐµÐº',
		'close': 'Ð—Ð°ÐºÑ€Ñ‹Ñ‚ÑŒ',
		'send': 'ÐžÑ‚Ð¿Ñ€Ð°Ð²Ð¸Ñ‚ÑŒ',
		'history': 'Ð˜ÑÑ‚Ð¾Ñ€Ð¸Ñ',
		'keys': 'ÐšÐ»ÑŽÑ‡Ð¸',
		'reset': 'Ð¡Ð±Ñ€Ð¾ÑÐ¸Ñ‚ÑŒ',
		'available-balance': 'Ð”Ð¾ÑÑ‚ÑƒÐ¿Ð½Ñ‹Ð¹ Ð±Ð°Ð»Ð°Ð½Ñ:',
		'enter-address': 'Ð’Ð²ÐµÐ´Ð¸Ñ‚Ðµ Ð°Ð´Ñ€ÐµÑ',
		'amount': 'Ð¡ÑƒÐ¼Ð¼Ð°',
		'fee': 'ÐšÐ¾Ð¼Ð¸ÑÑÐ¸Ñ',
		'recommended': 'Ñ€ÐµÐºÐ¾Ð¼ÐµÐ½Ð´Ð¾Ð²Ð°Ð½Ð¾',
		'loading': 'Ð—Ð°Ð³Ñ€ÑƒÐ·ÐºÐ°...',
		'send-sure': 'Ð’Ñ‹ ÑƒÐ²ÐµÑ€ÐµÐ½Ñ‹?',
		'send-processing': 'ÐžÐ±Ñ€Ð°Ð±Ð¾Ñ‚ÐºÐ°...',
		'success': 'Ð£ÑÐ¿ÐµÑ…',
		'failed': 'ÐÐµÑƒÐ´Ð°Ñ‡Ð°',
		'send-it': 'Ð”Ð°, Ð¾Ñ‚Ð¿Ñ€Ð°Ð²Ð¸Ñ‚ÑŒ!',
		'cancel': 'ÐžÑ‚Ð¼ÐµÐ½Ð¸Ñ‚ÑŒ',
		'send-warning': 'Ð’Ñ‹ Ð² Ð¾Ð´Ð½Ð¾Ð¼ ÑˆÐ°Ð³Ðµ Ð¾Ñ‚ Ñ‚Ð¾Ð³Ð¾, Ñ‡Ñ‚Ð¾Ð±Ñ‹ Ð¾Ñ‚Ð¿Ñ€Ð°Ð²Ð¸Ñ‚ÑŒ',
		'send-warning-reverse': 'Ð­Ñ‚Ð¾ Ð´ÐµÐ¹ÑÑ‚Ð²Ð¸Ðµ <strong>Ð½Ðµ Ð¼Ð¾Ð¶ÐµÑ‚</strong> Ð±Ñ‹Ñ‚ÑŒ Ð¾Ñ‚Ð¼ÐµÐ½ÐµÐ½Ð¾. Ð’Ñ‹ Ð² ÑÑ‚Ð¾Ð¼ ÑƒÐ²ÐµÑ€ÐµÐ½Ñ‹?',
		'loading-utxo': 'Ð—Ð°Ð³Ñ€ÑƒÐ·ÐºÐ° UTXOs...',
		'transaction-creation': 'Ð¡Ð¾Ð·Ð´Ð°Ð½Ð¸Ðµ Ñ‚Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ð¸Ð¸...',
		'transaction-broadcasted': 'Ð¢Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ð¸Ñ ÑƒÑÐ¿ÐµÑˆÐ½Ð° Ñ‚Ñ€Ð°Ð½ÑÐ»Ð¸Ñ€Ð¾Ð²Ð°Ð½Ð°: ',
		'close': 'Ð—Ð°ÐºÑ€Ñ‹Ñ‚ÑŒ',
		'address-type-changed': 'Ð¢Ð¸Ð¿ Ð°Ð´Ñ€ÐµÑÐ° Ð¸Ð·Ð¼ÐµÐ½ÐµÐ½ Ð½Ð°',
		'backend-switched': 'Ð‘ÑÐºÑÐ½Ð´ Ð¸Ð·Ð¼ÐµÐ½ÐµÐ½ Ð½Ð°',
		'backend-down': 'Ð½Ðµ Ð´Ð¾ÑÑ‚ÑƒÐ¿ÐµÐ½',
		'wallet-api': 'API Ð±ÑÐºÑÐ½Ð´ ÐºÐ¾ÑˆÐµÐ»ÑŒÐºÐ°',
		'open-wallet': 'ÐžÑ‚ÐºÑ€Ñ‹Ñ‚ÑŒ ÐšÐ¾ÑˆÐµÐ»ÐµÐº',
		'bad-utxo': 'ÐÐµÐ¿Ð¾Ð´Ð´ÐµÑ€Ð¶Ð¸Ð²Ð°ÐµÐ¼Ñ‹Ð¹ Ñ‚Ð¸Ð¿ UTXO!',
		'balance-load-failed': 'ÐœÑ‹ Ð½Ðµ Ð¼Ð¾Ð¶ÐµÐ¼ Ð·Ð°Ð³Ñ€ÑƒÐ·Ð¸Ñ‚ÑŒ Ð±Ð°Ð»Ð°Ð½Ñ ÐºÐ¾ÑˆÐµÐ»ÑŒÐºÐ°!',
		'not-enough-funds': 'Ð£ Ð’Ð°Ñ Ð½ÐµÐ´Ð¾ÑÑ‚Ð°Ñ‚Ð¾Ñ‡Ð½Ð¾ Ð´ÐµÐ½ÐµÐ¶Ð½Ñ‹Ñ… ÑÑ€ÐµÐ´ÑÑ‚Ð² Ð´Ð»Ñ ÑÑ‚Ð¾Ð¹ Ñ‚Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ð¸Ð¸!',
		'not-valid-address': 'Ð’Ñ‹ Ð´Ð¾Ð»Ð¶Ð½Ñ‹ ÑƒÐºÐ°Ð·Ð°Ñ‚ÑŒ Ð´ÐµÐ¹ÑÑ‚Ð²Ð¸Ñ‚ÐµÐ»ÑŒÐ½Ñ‹Ð¹ Ð°Ð´Ñ€ÐµÑ!',
		'not-valid-amount': 'Ð’Ñ‹ Ð´Ð¾Ð»Ð¶Ð½Ñ‹ ÑƒÐºÐ°Ð·Ð°Ñ‚ÑŒ Ð´ÐµÐ¹ÑÑ‚Ð²Ð¸Ñ‚ÐµÐ»ÑŒÐ½ÑƒÑŽ ÑÑƒÐ¼Ð¼Ñƒ!',
		'not-valid-fee': 'Ð’Ñ‹ Ð´Ð¾Ð»Ð¶Ð½Ñ‹ ÑƒÐºÐ°Ð·Ð°Ñ‚ÑŒ Ð´ÐµÐ¹ÑÑ‚Ð²Ð¸Ñ‚ÐµÐ»ÑŒÐ½ÑƒÑŽ ÐºÐ¾Ð¼Ð¸ÑÑÐ¸ÑŽ!',
		'bad-priv-key': 'ÐÐµÐ²ÐµÑ€Ð½Ñ‹Ð¹ Ð¿Ñ€Ð¸Ð²Ð°Ñ‚Ð½Ñ‹Ð¹ ÐºÐ»ÑŽÑ‡ WIF!',
		'not-enough-utxo': 'ÐÐµÐ´Ð¾ÑÑ‚Ð°Ñ‚Ð¾Ñ‡Ð½Ð¾ UTXO :(',
		'broadcast-failed': 'ÐÐµ ÑƒÐ´Ð°Ð»Ð¾ÑÑŒ Ñ‚Ñ€Ð°Ð½ÑÐ»Ð¸Ñ€Ð¾Ð²Ð°Ñ‚ÑŒ Ñ‚Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ð¸ÑŽ :(',
		'pass-not-match': 'Ð’Ð°ÑˆÐ¸ Ð¿Ð°Ñ€Ð¾Ð»Ð¸ Ð½Ðµ ÑÐ¾Ð²Ð¿Ð°Ð´Ð°ÑŽÑ‚!',
		'pass-too-short': 'Ð’Ð°Ñˆ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ Ð´Ð¾Ð»Ð¶ÐµÐ½ Ð±Ñ‹Ñ‚ÑŒ Ð½Ðµ Ð¼ÐµÐ½ÑŒÑˆÐµ 10 ÑÐ¸Ð¼Ð²Ð¾Ð»Ð¾Ð²!',
		'bad-email': 'ÐŸÐ¾Ñ…Ð¾Ð¶Ðµ, Ð’Ñ‹ Ð²Ð²ÐµÐ»Ð¸ Ð½Ðµ Ð´ÐµÐ¹ÑÑ‚Ð²Ð¸Ñ‚ÐµÐ»ÑŒÐ½Ñ‹Ð¹ ÑÐ»ÐµÐºÑ‚Ñ€Ð¾Ð½Ð½Ñ‹Ð¹ Ð°Ð´Ñ€ÐµÑ!',
		'small-fee': 'Ð’Ñ‹ Ð´Ð¾Ð»Ð¶Ð½Ñ‹ ÑƒÐºÐ°Ð·Ð°Ñ‚ÑŒ ÐºÐ¾Ð¼Ð¸ÑÑÐ¸ÑŽ Ð½Ðµ Ð¼ÐµÐ½ÑŒÑˆÐµ, Ñ‡ÐµÐ¼'
	},
	'kr': {
		'lang-alias': 'í•œêµ­ì–´',
		'wallet-title': 'ì§€ê°‘',
		'open-regular': 'ì¼ë°˜ ì§€ê°‘',
		'open-key': 'ê°œì¸í‚¤ë¡œ ì—´ê¸°',
		'disclaimer': 'ì´ íŽ˜ì´ì§€ëŠ” javascriptë¥¼ ì‚¬ìš©í•˜ì—¬ ì£¼ì†Œë¥¼ ìƒì„±í•˜ê³  ë¸Œë¼ìš°ì € ë‚´ì—ì„œ ê±°ëž˜ì— ì„œëª…í•©ë‹ˆë‹¤. ì¦‰, ê°œì¸í‚¤ë¥¼ ì ˆëŒ€ ë°›ì§€ ì•ŠìŠµë‹ˆë‹¤. Github ì†ŒìŠ¤ ì½”ë“œë¥¼ í†µí•˜ì—¬ ì´ë¥¼ ê²€í† í•  ìˆ˜ ìžˆìŠµë‹ˆë‹¤.',
		'open-reminder': '<b>ì•Œë¦¼:</b> ê³„ì¢Œ ì •ë³´ë¥¼ ì•ˆì „í•˜ê²Œ ë³´ê´€í•´ì£¼ì„¸ìš”. ê·¸ë ‡ì§€ ì•Šìœ¼ë©´ ì½”ì¸ì„ ì˜ì›ížˆ ìžƒì„ ìˆ˜ ìžˆìŠµë‹ˆë‹¤.',
		'open': 'ì—´ê¸°',
		'home': 'í™ˆ',
		'create': 'ìƒì„±',
		'broadcast': 'ë¸Œë¡œë“œìºìŠ¤íŠ¸',
		'settings': 'ì„¤ì •',
		'email-address': 'ë©”ì¼ ì£¼ì†Œ',
		'password': 'ë¹„ë°€ë²ˆí˜¸',
		'password-confirm': 'ë¹„ë°€ë²ˆí˜¸ í™•ì¸',
		'generate-question': 'ì•„ì§ ì§€ê°‘ì´ ì—†ìœ¼ì‹ ê°€ìš”?',
		'generate-it': '<a href="#/create">ìƒì„±í•˜ëŸ¬ ê°€ê¸°!</a>',
		'wif-key': 'WIF ê°œì¸í‚¤',
		'create-wallet': 'ì§€ê°‘ ìƒì„±í•˜ê¸°',
		'show': 'í‘œì‹œí•˜ê¸°',
		'hide': 'ìˆ¨ê¸°ê¸°',
		'address': 'ì£¼ì†Œ',
		'public-key': 'ê³µê°œí‚¤',
		'private-key': 'ê°œì¸í‚¤',
		'broadcast-transaction': 'ê±°ëž˜ ë¸Œë¡œë“œìºìŠ¤íŠ¸',
		'enter-transaction': 'ì„œëª…ëœ ê±°ëž˜ë¥¼ ìž…ë ¥í•´ì£¼ì„¸ìš”.',
		'wallet-settings': 'ì§€ê°‘ ì„¤ì •',
		'address-type': 'ì£¼ì†Œ í˜•ì‹',
		'wallet-backend': 'ì§€ê°‘ ë°±ì•¤ë“œ',
		'update': 'ê°±ì‹ ',
		'wallet-language': 'ì§€ê°‘ ì–¸ì–´',
		'version': 'ë²„ì „:',
		'wallet': 'ì§€ê°‘',
		'close': 'ë‹«ê¸°',
		'send': 'ë³´ë‚´ê¸°',
		'history': 'ê±°ëž˜ë‚´ì—­',
		'keys': 'ì§€ê°‘í‚¤',
		'reset': 'ì´ˆê¸°í™”',
		'available-balance': 'ì´ìš© ê°€ëŠ¥í•œ ìž”ì•¡:',
		'enter-address': 'ì£¼ì†Œ ìž…ë ¥',
		'amount': 'ì „ì†¡ëŸ‰',
		'fee': 'ìˆ˜ìˆ˜ë£Œ',
		'recommended': 'ì¶”ì²œ',
		'loading': 'ë¡œë“œì¤‘...',
		'send-sure': 'ì „ì†¡í•˜ì‹œê² ìŠµë‹ˆê¹Œ?',
		'send-processing': 'ì²˜ë¦¬ì¤‘...',
		'success': 'ì„±ê³µ',
		'failed': 'ì‹¤íŒ¨',
		'send-it': 'ì •ìƒì ìœ¼ë¡œ ì „ì†¡ë˜ì—ˆìŠµë‹ˆë‹¤!',
		'cancel': 'ì·¨ì†Œ',
		'send-warning': 'ë‹¤ìŒê³¼ ê°™ì´ ì „ì†¡í•˜ê³ ìž í•©ë‹ˆë‹¤',
		'send-warning-reverse': 'ì´ ìž‘ì—…ì„ ì‹œë„í•˜ë©´ <strong>ì·¨ì†Œí•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤.</strong> ì‚­ì œ í•˜ì‹œê² ìŠµë‹ˆê¹Œ?',
		'loading-utxo': 'UTXOs ë¡œë“œì¤‘...',
		'transaction-creation': 'ê±°ëž˜ ìƒì„± ì¤‘...',
		'transaction-broadcasted': 'ê±°ëž˜ ë¸Œë¡œë“œìºìŠ¤íŠ¸ ì„±ê³µ: ',
		'close': 'ë‹«ê¸°',
		'address-type-changed': 'ì •ìƒì ìœ¼ë¡œ ì£¼ì†Œ í˜•ì‹ì´ ë³€ê²½ë˜ì—ˆìŠµë‹ˆë‹¤.',
		'backend-switched': 'ì •ìƒì ìœ¼ë¡œ ë°±ì•¤ë“œê°€ ë³€ê²½ë˜ì—ˆìŠµë‹ˆë‹¤.',
		'backend-down': 'ì‚¬ìš©í•  ìˆ˜ ì—†ëŠ” ë°±ì•¤ë“œ ìž…ë‹ˆë‹¤.',
		'wallet-api': 'ì§€ê°‘ API ë°±ì•¤ë“œ',
		'open-wallet': 'ì§€ê°‘ ì—´ê¸°',
		'bad-utxo': 'ì§€ì›ë˜ì§€ ì•ŠëŠ” UTXO í˜•ì‹ ìž…ë‹ˆë‹¤.',
		'balance-load-failed': 'ì§€ê°‘ ìž”ì•¡ ë¶ˆëŸ¬ì˜¤ê¸° ì‹¤íŒ¨!',
		'not-enough-funds': 'ì „ì†¡ì— í•„ìš”í•œ ìž”ì•¡ì´ ë¶€ì¡±í•©ë‹ˆë‹¤.',
		'not-valid-address': 'ì˜¬ë°”ë¥¸ ì§€ê°‘ ì£¼ì†Œê°€ ì•„ë‹™ë‹ˆë‹¤.',
		'not-valid-amount': 'ì˜¬ë°”ë¥¸ ì „ì†¡ëŸ‰ì´ ì•„ë‹™ë‹ˆë‹¤.',
		'not-valid-fee': 'ì˜¬ë°”ë¥¸ ìˆ˜ìˆ˜ë£Œê°€ ì•„ë‹™ë‹ˆë‹¤.',
		'bad-priv-key': 'ìž˜ëª»ëœ WIFê°œì¸í‚¤ ìž…ë‹ˆë‹¤.',
		'not-enough-utxo': 'UTXOì´ ë¶€ì¡±í•©ë‹ˆë‹¤. :(',
		'broadcast-failed': 'ê±°ëž˜ ë¸Œë¡œë“œìºìŠ¤íŠ¸ì— ì‹¤íŒ¨í•˜ì˜€ìŠµë‹ˆë‹¤. :(',
		'pass-not-match': 'ë¹„ë°€ë²ˆí˜¸ê°€ ì¼ì¹˜í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤.',
		'pass-too-short': 'ë¹„ë°€ë²ˆí˜¸ëŠ” 10ê¸€ìž ì´ìƒ ìž…ë ¥í•´ì£¼ì„¸ìš”.',
		'bad-email': 'ì˜¬ë°”ë¥¸ ë©”ì¼ ì£¼ì†Œê°€ ì•„ë‹™ë‹ˆë‹¤.',
		'small-fee': 'ìµœì†Œìˆ˜ìˆ˜ë£Œ'
	},
	'de': {
		'lang-alias': 'Deutsch',
		'wallet-title': 'Wallet',
		'open-regular': 'RegulÃ¤re Wallet',
		'open-key': 'Mit SchlÃ¼ssel Ã¶ffnen',
		'disclaimer': 'Dieses Wallet benutzt JavaScript um Deine Adressen zu generieren und Transaktionen im Browser zu signieren. Zu keinem Zeitpunkt wird hierbei dein PrivatschlÃ¼ssel dauerhaft gespeichert!! Zur ÃœberprÃ¼fung kann der Quellcode jederzeit im GitHub eingesehen werden.',
		'open-reminder': '<b>Notice:</b> Sorge bitte dafÃ¼r dich an deine Kontodaten erinnern zu kÃ¶nnen um nicht den Zugriff zu deinem Konto und dessen Guthaben zu verlieren!',
		'open': 'Ã–ffnen',
		'home': 'Startseite',
		'create': 'Erstellen',
		'broadcast': 'Ãœbertragung',
		'settings': 'Einstellungen',
		'email-address': 'Email Addresse',
		'password': 'Passwort',
		'password-confirm': 'Passwort bestÃ¤tigen',
		'generate-question': 'Du hast noch keine Wallet',
		'generate-it': '<a href="#/create">Hier Wallet erstellen</a> it!',
		'wif-key': 'Privater SchlÃ¼ssel (WIF)',
		'create-wallet': 'Wallet erstellen',
		'show': 'Anzeigen',
		'hide': 'Verbergen',
		'address': 'Addresse',
		'public-key': 'Ã–ffentlicher SchlÃ¼ssel',
		'private-key': 'Privater SchlÃ¼ssel',
		'broadcast-transaction': 'Transaktion senden',
		'enter-transaction': 'Signierte Transaktion eintragen',
		'wallet-settings': 'Wallet-Einstellungen',
		'address-type': 'Addresstyp',
		'wallet-backend': 'Wallet Backend',
		'update': 'Aktualisieren',
		'wallet-language': 'Wallet Sprachwahl',
		'version': 'Version:',
		'wallet': 'Wallet',
		'close': 'SchlieÃŸen',
		'send': 'Senden',
		'history': 'Verlauf',
		'keys': 'SchlÃ¼ssel',
		'reset': 'Reset',
		'available-balance': 'VerfÃ¼gbares Guthaben:',
		'enter-address': 'Adresse eingeben',
		'amount': 'Betrag',
		'fee': 'TransaktionsgebÃ¼hr',
		'recommended': 'empfohlen',
		'loading': 'Lade...',
		'send-sure': 'Bist du sicher?',
		'send-processing': 'Verarbeitung lÃ¤uft...',
		'success': 'Aktion erfolgreich',
		'failed': 'Aktion fehlgeschlagen',
		'send-it': 'Ja, bitte senden!',
		'cancel': 'Abbruch',
		'send-warning': 'Du bist dabei, eine Zahlung zu senden',
		'send-warning-reverse': 'Diese Aktion kann<strong>nicht rÃ¼ckgÃ¤ngig</strong> gemacht werden. Bist Du wirklich sicher?',
		'loading-utxo': 'Lade UTXOen...',
		'transaction-creation': 'Transaktion wird erstellt...',
		'transaction-broadcasted': 'Transaktion erfolgreich gesendet: ',
		'close': 'SchlieÃŸen',
		'address-type-changed': 'Adresstyp geÃ¤ndert in',
		'backend-switched': 'Backend geÃ¤ndert zu',
		'backend-down': 'scheint gerade nicht verfÃ¼gbar zu sein',
		'wallet-api': 'Wallet API backend',
		'open-wallet': 'Wallet Ã¶ffnen',
		'bad-utxo': 'Nicht unterstÃ¼tzter UTXO Typ!',
		'balance-load-failed': 'Kontostand konnte nicht geladen werden!',
		'not-enough-funds': 'Dein Guthaben ist fÃ¼r diese Transaktion nicht ausreichend!',
		'not-valid-address': 'Bitte gib eine gÃ¼ltige Adresse ein!',
		'not-valid-amount': 'Bitte gib einen gÃ¼ltigen Betrag ein!',
		'not-valid-fee': 'Bitte gib eine gÃ¼ltige TransaktionsgebÃ¼hr ein!',
		'bad-priv-key': 'UngÃ¼ltiger oder falscher WIF-SchlÃ¼ssel',
		'not-enough-utxo': 'Nicht genÃ¼gend UTXO :(',
		'broadcast-failed': 'Sendung der Transaktion fehlgeschlagen :(',
		'pass-not-match': 'Die von Dir eingegebenen PasswÃ¶rter stimmen nicht Ã¼berein!',
		'pass-too-short': 'Die LÃ¤nge Deines Passworts muss mindestens 10 Zeichen betragen!',
		'bad-email': 'Deine Email-Adresse scheint nicht gÃ¼ltig zu sein!',
		'small-fee': 'sollte nicht weniger betragen als'
	}
}